#!/bin/bash

set -e

echo "Installing..."

# Verbose mode. Default: false.
VERBOSE="${VERBOSE:=false}"
SETUP_PY_OPTS="-q"
CURL_OPTS="--silent"
if [ "${VERBOSE}" = true ]; then
    set -x
    SETUP_PY_OPTS="-v"
    CURL_OPTS=""
fi
# Python's path that the module is installed on. Default: python3
PYTHON="${PYTHON:=python3}"
PYTHON="$(which "${PYTHON}")"
# Linked rpm's path. Default: rpm.
RPM="${RPM:=rpm}"
RPM="$(which "${RPM}")"
# Installed RPM Python module's version. Default: Same version with rpm.
DEFAULT_RPM_VERSION=$("${RPM}" --version | cut -d' ' -f 3)
RPM_VERSION="${RPM_VERSION:=${DEFAULT_RPM_VERSION}}"

# Check if Python is system Python.
if [[ "${PYTHON}" =~ ^/usr/bin/python.*$ ]]; then
    # Check the Python binding is not installed.
    RESULT=$("${PYTHON}" -m pip list)
    if ! echo "${RESULT}" | grep -E '^rpm(-python)? +' -q; then
        cat 1>&2 <<EOF
Skipped installing RPM python binding on system Python: ${PYTHON}.
Install it manually by "dnf install python{,2,3}-rpm".
Then run this installer again.
EOF
        exit 1
    fi
fi

# If RPM is System installed RPM
if [ "${RPM}" = "/usr/bin/rpm" ]; then
    # Check if rpm-libs is installed for /usr/lib64/librpm*.so
    if ! rpm -q rpm-libs --quiet; then
        cat 1>&2 <<EOF
rpm-libs is not installed.
Install it by "dnf install rpm-libs".
EOF
        exit 2
    fi

    # Check rpm-devel is installed for /usr/lib64/pkgconfig/rpm.pc
    if ! rpm -q rpm-devel --quiet; then
        cat 1>&2 <<EOF
rpm-devel is not installed.
Install it by "dnf install rpm-devel".
EOF
        exit 2
    fi
fi

WORK_DIR="$(mktemp -d --suffix="-rpm-py-installer")"
echo "Created working directory '${WORK_DIR}'"
cd "${WORK_DIR}"

RPM_REPO_URL='https://github.com/rpm-software-management/rpm'
RPM_NAME="rpm-${RPM_VERSION}-release"
ARCHIVE_FILE="${RPM_REPO_URL}/archive/${RPM_NAME}.tar.gz"

echo "Downloading archive '${ARCHIVE_FILE}' in the working directory."
curl --location ${CURL_OPTS} "${ARCHIVE_FILE}" | tar xz

cd "rpm-${RPM_NAME}/python"

sed -e 's/@PACKAGE_NAME@/rpm/g' \
    -e "s/@VERSION@/${RPM_VERSION}/g" \
    -e "s/@PACKAGE_BUGREPORT@/rpm-maint@lists.rpm.org/g" \
    setup.py.in \
    > setup.py

# rpm-libs and rpm-devel are required to build.
echo "Building the Python binding module on Python: '${PYTHON}'."
"${PYTHON}" setup.py ${SETUP_PY_OPTS} build
"${PYTHON}" setup.py ${SETUP_PY_OPTS} install

# Check the Python binding is installed.
INSTALLED_RPM_PY=$("${PYTHON}" -m pip list | grep -E '^rpm(-python)? +')
echo "RPM Python binding module installed: ${INSTALLED_RPM_PY}"

echo "Done successfully."

exit 0
