FROM centos

WORKDIR /build
COPY . .

RUN yum -y update
RUN yum -y install epel-release
RUN yum -y install \
  --setopt=deltarpm=0 \
  --setopt=install_weak_deps=false \
  --setopt=tsflags=nodocs \
  rpm-libs \
  rpm-devel \
  redhat-rpm-config \
  gcc \
  python34-devel \
  python-devel \
  /usr/bin/python3.4 \
  /usr/bin/python2.7 \
  && yum clean all
RUN python3 -m ensurepip
RUN python3 -m pip install --upgrade pip setuptools
RUN python3 -m pip install tox

CMD ["/usr/bin/tox"]
