FROM ubuntu:trusty

WORKDIR /build
COPY tox-py34-requirements.txt .

RUN apt-get update
RUN apt-get install -y \
  -o Dpkg::Options::='--force-confnew' \
  # -- RPM packages required for installing --
  rpm \
  python3.4-dev \
  python2.7-dev \
  python3-pip \
  # -- RPM packages required for a specified case --
  git
RUN apt-get clean all
RUN python3 -m pip install --upgrade -rtox-py34-requirements.txt
