name: Build test images and run the tests
on:
  push:
  pull_request:
  schedule:
    - cron: '0 20 * * 2'
jobs:
  matrix-preparation:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        uses: JoshuaTheMiller/conditional-build-matrix@0.1.0
        with:
          filter: '[?!cron || `${{ env.GITHUB_EVENT_NAME }}` == `schedule`]'
  build-and-test:
    needs: matrix-preparation
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.matrix-preparation.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - if: ${{ matrix.docker }}
        run: echo "DOCKER=${{ matrix.docker }}" >> $GITHUB_ENV
      - if: ${{ matrix.dockerfile }}
        run: echo "DOCKERFILE=${{ matrix.dockerfile }}" >> $GITHUB_ENV
      - if: ${{ matrix.docker_volume }}
        run: echo "DOCKER_VOLUME=${{ matrix.docker_volume }}" >> $GITHUB_ENV
      - if: ${{ matrix.image }}
        run: echo "IMAGE=${{ matrix.image }}" >> $GITHUB_ENV
      - if: ${{ matrix.toxenv }}
        run: echo "TOXENV=${{ matrix.toxenv }}" >> $GITHUB_ENV
      - if: ${{ matrix.test_lint }}
        run: echo "TEST_LINT=${{ matrix.test_lint }}" >> $GITHUB_ENV
      - name: Build test images
        run: make ${{ matrix.targets }}
      - name: Run the tests
        run: make test
