name: publish
on:
  push:
    tags:        
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Build a source tarball and a binary wheel
        run: |
          python -m pip install build
          python -m build --sdist --wheel
      - name: Publish the package on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
